name: Check PR title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v2.2.5
        with:
          success-state: Title follows the specification.
          failure-state: Title does not follow the specification.
          preset: conventional-changelog-angular@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
